export const GET_ALL_COLLECTIONS = 'GET_ALL_COLLECTIONS';
export const GET_ALL_COLLECTIONS_SUCCESS = 'GET_ALL_COLLECTIONS_SUCCESS';
export const GET_ALL_COLLECTIONS_FAILED = 'GET_ALL_COLLECTIONS_FAILED';

export const GET_USER_COLLECTIONS = 'GET_USER_COLLECTIONS';
export const GET_USER_COLLECTIONS_SUCCESS = 'GET_USER_COLLECTIONS_SUCCESS';
export const GET_USER_COLLECTIONS_FAILED = 'GET_USER_COLLECTIONS_FAILED';

export const GET_MY_COLLECTION = 'GET_MY_COLLECTION';
export const GET_MY_COLLECTION_SUCCESS = 'GET_MY_COLLECTION_SUCCESS';
export const GET_MY_COLLECTION_FAILED = 'GET_MY_COLLECTION_FAILED';

export const CREATE_COLLECTION = 'CREATE_COLLECTION';
export const CREATE_COLLECTION_SUCCESS = 'CREATE_COLLECTION_SUCCESS';
export const CREATE_COLLECTION_FAILED = 'CREATE_COLLECTION_FAILED';

export const APPROVE_COLLECTION = 'APPROVE_COLLECTION';
export const APPROVE_COLLECTION_SUCCESS = 'APPROVE_COLLECTION_SUCCESS';
export const APPROVE_COLLECTION_FAILED = 'APPROVE_COLLECTION_FAILED';

export const DECLINE_COLLECTION = 'DECLINE_COLLECTION';
export const DECLINE_COLLECTION_SUCCESS = 'DECLINE_COLLECTION_SUCCESS';
export const DECLINE_COLLECTION_FAILED = 'DECLINE_COLLECTION_FAILED';

export const UPDATE_COLLECTION_ADDRESS = 'UPDATE_COLLECTION_ADDRESS';
export const UPDATE_COLLECTION_ADDRESS_SUCCESS = 'UPDATE_COLLECTION_ADDRESS_SUCCESS';
export const UPDATE_COLLECTION_ADDRESS_FAILED = 'UPDATE_COLLECTION_ADDRESS_FAILED';

export const REMOVE_COLLECTION = 'REMOVE_COLLECTION';
export const REMOVE_COLLECTION_SUCCESS = 'REMOVE_COLLECTION_SUCCESS';
export const REMOVE_COLLECTION_FAILED = 'REMOVE_COLLECTION_FAILED';
