export const GET_ALL_BRANDS = 'GET_ALL_BRANDS';
export const GET_ALL_BRANDS_SUCCESS = 'GET_ALL_BRANDS_SUCCESS';
export const GET_ALL_BRANDS_FAILED = 'GET_ALL_BRANDS_FAILED';

export const GET_USER_BRAND = 'GET_USER_BRAND';
export const GET_USER_BRAND_SUCCESS = 'GET_USER_BRAND_SUCCESS';
export const GET_USER_BRAND_FAILED = 'GET_USER_BRAND_FAILED';

export const CREATE_BRAND = 'CREATE_BRAND';
export const CREATE_BRAND_SUCCESS = 'CREATE_BRAND_SUCCESS';
export const CREATE_BRAND_FAILED = 'CREATE_BRAND_FAILED';

export const APPROVE_BRAND = 'APPROVE_BRAND';
export const APPROVE_BRAND_SUCCESS = 'APPROVE_BRAND_SUCCESS';
export const APPROVE_BRAND_FAILED = 'APPROVE_BRAND_FAILED';

export const DECLINE_BRAND = 'DECLINE_BRAND';
export const DECLINE_BRAND_SUCCESS = 'DECLINE_BRAND_SUCCESS';
export const DECLINE_BRAND_FAILED = 'DECLINE_BRAND_FAILED';
