export const GET_MARKET_PLACE = 'GET_MARKET_PLACE';
export const GET_MARKET_PLACE_SUCCESS = 'GET_MARKET_PLACE_SUCCESS';
export const GET_MARKET_PLACE_FAILED = 'GET_MARKET_PLACE_FAILED';

export const SELL_NFT = 'SELL_NFT';
export const SELL_NFT_SUCCESS = 'SELL_NFT_SUCCESS';
export const SELL_NFT_FAILED = 'SELL_NFT_FAILED';

export const BUY_NFT = 'BUY_NFT';
export const BUY_NFT_SUCCESS = 'BUY_NFT_SUCCESS';
export const BUY_NFT_FAILED = 'BUY_NFT_FAILED';
